/*
 * Copyright (c) 2017, info@mimidots.com
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

package sms_project;

import java.awt.Component;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.UIManager;


public class MainUI extends javax.swing.JFrame {

    /** Creates new form MainUI */
    int x,y;
    public MainUI() {
        initComponents();
        /*set the initial view as send sms panel*/
        Component add = this.rootPanel.add(new Dashboard());
//         Component ad = this.rootPanel.add(new reg());
       
        
        eventHandler();
    }

    private void eventHandler(){
        jBtnHome.addActionListener((e) -> {
            changeView(new Dashboard());
        });
        
        jBtnStudent.addActionListener((e) -> {
           changeView(new reg());
        });
         jBtnParent.addActionListener((e) -> {
            changeView(new Parents());
        });
        jBtnMessages.addActionListener((e) -> {
            changeView(new SendSMS());
        });
          jBnViewMsg.addActionListener((e) -> {
            changeView(new SMSLogs());
        });
            jBtManage.addActionListener((e) -> {
            changeView(new updateParent());
        });
           
            jBtDisplay.addActionListener((e) -> {
            changeView(new DisplayExecutives());
        });
        
        jBtFee.addActionListener((e) -> {
            changeView(new fees());
        });
        
        
    }
    
    private void changeView(JPanel p){
        this.rootPanel.removeAll();
        this.rootPanel.add(p);
        this.rootPanel.revalidate();
        this.rootPanel.repaint();
    }
         
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBtnHome = new javax.swing.JButton();
        jBtnStudent = new javax.swing.JButton();
        jBnViewMsg = new javax.swing.JButton();
        jBtnParent = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jBtnMessages = new javax.swing.JButton();
        jBtManage = new javax.swing.JButton();
        jBtFee = new javax.swing.JButton();
        jBtDisplay = new javax.swing.JButton();
        jBtHelp2 = new javax.swing.JButton();
        rootPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1360, 749));

        jPanel1.setBackground(new java.awt.Color(153, 0, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Quick Access", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 13), new java.awt.Color(255, 255, 255))); // NOI18N

        jBtnHome.setBackground(new java.awt.Color(204, 204, 255));
        jBtnHome.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jBtnHome.setForeground(new java.awt.Color(153, 0, 102));
        jBtnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms_project/images/Dashboard_30px_3.png"))); // NOI18N
        jBtnHome.setText("DashBoard");
        jBtnHome.setAutoscrolls(true);
        jBtnHome.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new javax.swing.ImageIcon(getClass().getResource("/sms_project/images/Dashboard_30px_2.png")))); // NOI18N
        jBtnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnHomeActionPerformed(evt);
            }
        });

        jBtnStudent.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jBtnStudent.setForeground(new java.awt.Color(153, 0, 102));
        jBtnStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms_project/images/Add User Male_30px_1.png"))); // NOI18N
        jBtnStudent.setText("MEMBERS");
        jBtnStudent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnStudentActionPerformed(evt);
            }
        });

        jBnViewMsg.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jBnViewMsg.setForeground(new java.awt.Color(153, 0, 102));
        jBnViewMsg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms_project/images/Read Message_30px.png"))); // NOI18N
        jBnViewMsg.setText("READ MESSAGE");
        jBnViewMsg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBnViewMsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnViewMsgActionPerformed(evt);
            }
        });

        jBtnParent.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jBtnParent.setForeground(new java.awt.Color(153, 0, 102));
        jBtnParent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms_project/images/Parenting_30px_3.png"))); // NOI18N
        jBtnParent.setText("EXECUTIVES");
        jBtnParent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnParent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnParentActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms_project/images/Search_30px.png"))); // NOI18N

        jTextField1.setBackground(new java.awt.Color(153, 0, 102));
        jTextField1.setForeground(new java.awt.Color(153, 255, 255));
        jTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        jBtnMessages.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jBtnMessages.setForeground(new java.awt.Color(153, 0, 102));
        jBtnMessages.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms_project/images/SMS_30px_1.png"))); // NOI18N
        jBtnMessages.setText("MESSAGES");
        jBtnMessages.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnMessages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMessagesActionPerformed(evt);
            }
        });

        jBtManage.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jBtManage.setForeground(new java.awt.Color(153, 0, 102));
        jBtManage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms_project/images/Update_30px.png"))); // NOI18N
        jBtManage.setText("MANAGE RECORDS");
        jBtManage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtManageActionPerformed(evt);
            }
        });

        jBtFee.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jBtFee.setForeground(new java.awt.Color(153, 0, 102));
        jBtFee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms_project/images/Money Pound_30px.png"))); // NOI18N
        jBtFee.setText("FEES");
        jBtFee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtFee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtFeeActionPerformed(evt);
            }
        });

        jBtDisplay.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jBtDisplay.setForeground(new java.awt.Color(153, 0, 102));
        jBtDisplay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms_project/images/Open_30px.png"))); // NOI18N
        jBtDisplay.setText("Display Records");
        jBtDisplay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtDisplayActionPerformed(evt);
            }
        });

        jBtHelp2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jBtHelp2.setForeground(new java.awt.Color(153, 0, 102));
        jBtHelp2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms_project/images/Help_30px_2.png"))); // NOI18N
        jBtHelp2.setText("HELP");
        jBtHelp2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtHelp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtHelp2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1))
            .addComponent(jBtnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jBtnStudent, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
            .addComponent(jBtnParent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jBtnMessages, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jBnViewMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jBtManage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jBtFee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jBtDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jBtHelp2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnParent, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnMessages, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBnViewMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtManage, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtFee, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtHelp2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        rootPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 102), 1, true)));
        rootPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rootPanel.setLayout(new java.awt.GridBagLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        setSize(new java.awt.Dimension(840, 683));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnMessagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMessagesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnMessagesActionPerformed

    private void jBtnStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnStudentActionPerformed
     
    }//GEN-LAST:event_jBtnStudentActionPerformed

    private void jBtnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnHomeActionPerformed

    private void jBtnParentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnParentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnParentActionPerformed

    private void jBnViewMsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnViewMsgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBnViewMsgActionPerformed

    private void jBtManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtManageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtManageActionPerformed

    private void jBtFeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtFeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtFeeActionPerformed

    private void jBtDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtDisplayActionPerformed

    private void jBtHelp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtHelp2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtHelp2ActionPerformed

   
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {

}

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBnViewMsg;
    private javax.swing.JButton jBtDisplay;
    private javax.swing.JButton jBtFee;
    private javax.swing.JButton jBtHelp2;
    private javax.swing.JButton jBtManage;
    private javax.swing.JButton jBtnHome;
    private javax.swing.JButton jBtnMessages;
    private javax.swing.JButton jBtnParent;
    private javax.swing.JButton jBtnStudent;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel rootPanel;
    // End of variables declaration//GEN-END:variables

}
