/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sms_project;

import com.sun.glass.events.KeyEvent;
import static com.sun.webkit.perf.WCGraphicsPerfLogger.reset;
import database.Mysql;
import java.awt.Color;
import java.awt.event.KeyListener;
import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author CollyneJumah
 */
public class reg extends javax.swing.JPanel {
    public Connection getConnection(){
        Connection conn;
        try{
            conn=DriverManager.getConnection("jdbc:mysql://localhost/cu","root","");
            return conn;
        
        }catch(Exception ex){
        ex.printStackTrace();
        return null;
        }
    }

    /**
     * Creates new form reg
     */
       public void executeSqlQuery(String query,String message){
       
             Connection conn=getConnection();
             Statement st;
            try{
                st=conn.createStatement();
                if(st.executeUpdate(query)==1){
                    DefaultTableModel model=(DefaultTableModel)tableShowMembers.getModel();
                    model.setRowCount(0);
                    showResultsOnTable();
                JOptionPane.showMessageDialog(null,"Data"+message+"Successsful");
                
                }else{
                    JOptionPane.showMessageDialog(null,"No Data"+message);
                }
                
            }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex.getLocalizedMessage());
            ex.printStackTrace();
            }
     }
   
    public reg() {
        initComponents();
        timer();
        date();
        showResultsOnTable();
        txtId.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        fName = new javax.swing.JLabel();
        lastName = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtFirst_Name = new javax.swing.JTextField();
        txtPhoneNumber = new javax.swing.JTextField();
        txtRegNumber = new javax.swing.JTextField();
        cboEt = new javax.swing.JComboBox();
        cboMinistry = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        txtLast_Name = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Radio_Male = new javax.swing.JRadioButton();
        Radio_Female = new javax.swing.JRadioButton();
        fName1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        CboYear = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        QuickSearch = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableShowMembers = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        labelShowTime = new javax.swing.JLabel();
        showDate = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1005, 617));

        jPanel1.setBackground(new java.awt.Color(153, 0, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 102)));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 102)), "Manage", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14), new java.awt.Color(153, 0, 102))); // NOI18N

        fName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        fName.setForeground(new java.awt.Color(153, 0, 102));
        fName.setText("First Name");

        lastName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lastName.setForeground(new java.awt.Color(153, 0, 102));
        lastName.setText("Last Name");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 102));
        jLabel4.setText("Phone");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 102));
        jLabel5.setText("Ministries");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 102));
        jLabel6.setText("Year");

        txtFirst_Name.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtFirst_Name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFirst_Name.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 0, 102)));
        txtFirst_Name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFirst_NameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFirst_NameKeyTyped(evt);
            }
        });

        txtPhoneNumber.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtPhoneNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPhoneNumber.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 0, 102)));
        txtPhoneNumber.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPhoneNumberMouseClicked(evt);
            }
        });
        txtPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneNumberActionPerformed(evt);
            }
        });
        txtPhoneNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPhoneNumberKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPhoneNumberKeyTyped(evt);
            }
        });

        txtRegNumber.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtRegNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtRegNumber.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 0, 102)));
        txtRegNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegNumberActionPerformed(evt);
            }
        });

        cboEt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cboEt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Select--ET--", "CET", "NET", "WESO", "RIVET", "ESET" }));
        cboEt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(51, 255, 0)));
        cboEt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboEtActionPerformed(evt);
            }
        });

        cboMinistry.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cboMinistry.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Select--Ministry--", "Praise & Worship", "Church School", "Choir", "Ushering & Hospitality", "Intercessory", "Creativity", "Instrunments", "High School" }));
        cboMinistry.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(51, 255, 0)));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 102));
        jLabel1.setText("ET");

        btnSave.setBackground(new java.awt.Color(153, 255, 153));
        btnSave.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms_project/images/Submit Progress_30px.png"))); // NOI18N
        btnSave.setText("Submit");
        btnSave.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(255, 51, 0));
        btnReset.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms_project/images/Reset_30px.png"))); // NOI18N
        btnReset.setText("Reset");
        btnReset.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReset.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                btnResetAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        txtLast_Name.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtLast_Name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtLast_Name.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 0, 102)));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 102));
        jLabel7.setText("Reg Number");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 0, 102));
        jLabel8.setText("Gender");

        Radio_Male.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(Radio_Male);
        Radio_Male.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Radio_Male.setText("Male");

        Radio_Female.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(Radio_Female);
        Radio_Female.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Radio_Female.setText("Female");

        fName1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        fName1.setForeground(new java.awt.Color(153, 0, 102));
        fName1.setText("Id");

        txtId.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 0, 102)));

        CboYear.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        CboYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Select--Year--", "First Year", "Second Year", "Third Year", "Fourth Year", "Associate" }));
        CboYear.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(51, 255, 0)));
        CboYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboYearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(Radio_Male, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Radio_Female))
                            .addComponent(txtRegNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fName, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fName1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtLast_Name)
                                    .addComponent(txtFirst_Name, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                    .addComponent(txtId)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cboMinistry, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CboYear, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cboEt, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fName1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFirst_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lastName)
                    .addComponent(txtLast_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(txtRegNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Radio_Male)
                    .addComponent(Radio_Female)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboMinistry, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(CboYear, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboEt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 102)), "Manage", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14), new java.awt.Color(153, 0, 102))); // NOI18N

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 102)), "Manage", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14), new java.awt.Color(153, 0, 102))); // NOI18N

        QuickSearch.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        QuickSearch.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        QuickSearch.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 0, 102)));
        QuickSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                QuickSearchKeyTyped(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(204, 204, 255));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms_project/images/Search_34px.png"))); // NOI18N
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(153, 0, 102));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms_project/images/Available Updates_34px.png"))); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(255, 255, 255));
        btnDelete.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(153, 0, 102));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms_project/images/Delete_34px.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(QuickSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(QuickSearch, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        tableShowMembers.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tableShowMembers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableShowMembers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableShowMembersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableShowMembers);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Wide Latin", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms_project/images/delete.png"))); // NOI18N
        jLabel9.setToolTipText("close");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        labelShowTime.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        labelShowTime.setForeground(new java.awt.Color(255, 255, 255));

        showDate.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        showDate.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(showDate, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelShowTime, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(showDate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelShowTime, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFirst_NameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFirst_NameKeyPressed
        lastName.setVisible(false);
        txtLast_Name.setVisible(false);
        
    }//GEN-LAST:event_txtFirst_NameKeyPressed

    private void txtPhoneNumberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPhoneNumberMouseClicked
        txtPhoneNumber.setText("+2547");
        String phone = txtPhoneNumber.getText();
        if(phone.length()==13){
            JOptionPane.showMessageDialog(this," Reach Maximum!");
        }
    }//GEN-LAST:event_txtPhoneNumberMouseClicked

    private void txtPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneNumberActionPerformed

    }//GEN-LAST:event_txtPhoneNumberActionPerformed

    private void txtPhoneNumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneNumberKeyPressed

    }//GEN-LAST:event_txtPhoneNumberKeyPressed

    private void txtPhoneNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneNumberKeyTyped
        char c = evt.getKeyChar();

        if (!((c >= '0') && (c <= '9') || (c == KeyEvent.VK_BACKSPACE) || (c == KeyEvent.VK_DELETE) || (c == KeyEvent.VK_ENTER))) {

            JOptionPane.showMessageDialog(null, "Enter Numerics Only");
            evt.consume();
        }       
        String phoneNumber=txtPhoneNumber.getText();

        if(phoneNumber.length()==13){
            evt.consume();
        }
    }//GEN-LAST:event_txtPhoneNumberKeyTyped

    private void txtRegNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegNumberActionPerformed

    }//GEN-LAST:event_txtRegNumberActionPerformed

    private void cboEtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboEtActionPerformed

    }//GEN-LAST:event_cboEtActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        insert();
     
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnResetAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_btnResetAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetAncestorAdded

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        reset();

    }//GEN-LAST:event_btnResetActionPerformed

    private void QuickSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_QuickSearchKeyTyped
        table_filter();
    }//GEN-LAST:event_QuickSearchKeyTyped

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String search=QuickSearch.getText();
        if(search.equals("")){
            QuickSearch.setBorder(new LineBorder(Color.red));
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // updateRecords();
        String Gender;
        if(Radio_Female.isSelected()){
            Gender="Female";
        }else{
            Gender="Male";
        }
        String Year=(String) CboYear.getSelectedItem();
        switch (Year) {
            case "First Year":
            Year="1";
            break;
            case "Second Year":
            Year="2";
            break;
            case "Third Year":
            Year="3";
            break;
            case "Fourth Year":
            Year="4";
            break;
        }
        String sql="UPDATE registermembers SET Name ='"+txtFirst_Name.getText()+"',Reg_Number ='"+txtRegNumber.getText()+"',Gender='"+Gender+"',PhoneNumber ='"+txtPhoneNumber.getText()+"',Ministry ='"+cboMinistry.getSelectedItem()+"',Year='"+Year+"',ET='"+cboEt.getSelectedItem()+"' WHERE Reg_Number='"+txtRegNumber.getText()+"'";
        executeSqlQuery(sql,"Record Updated!");
        txtLast_Name.setVisible(true);
        lastName.setVisible(true);
        fName.setVisible(true);
        reset();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        //   deleteRecords();
        String sql="DELETE FROM registermembers WHERE Reg_Number='"+txtRegNumber.getText()+"'";
        executeSqlQuery(sql,"Record Deleted!");
        txtLast_Name.setVisible(true);
        lastName.setVisible(true);
        fName.setVisible(true);
        reset();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tableShowMembersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableShowMembersMouseClicked
        //       deleteRecords();
        //       updateRecords();
//        set last name invisible 
        txtLast_Name.setVisible(false);
        lastName.setVisible(false);
        
        int count=0;
        int row= tableShowMembers.getSelectedRow();
        TableModel model= tableShowMembers.getModel();
        txtId.setText(model.getValueAt(row, 0).toString());
        txtFirst_Name.setText(model.getValueAt(row, 1).toString());
        txtRegNumber.setText(model.getValueAt(row, 2).toString());
        String gender=model.getValueAt(row, 3).toString();
        if(gender.equals("Male")){
            Radio_Male.setSelected(true);
        }else{
            Radio_Female.setSelected(true);
        }
        if(model.isCellEditable(row, 1)){
            lastName.setVisible(false);
            txtLast_Name.setVisible(false);
        }else{
            lastName.setVisible(true);
            txtLast_Name.setVisible(true);
        }

        txtPhoneNumber.setText(model.getValueAt(row, 4).toString());
        String Ministry=model.getValueAt(row, 5).toString();
        switch(Ministry){
            case "Praise & Worship":
            cboMinistry.setSelectedIndex(1);
            break;
            case "Church School":
            cboMinistry.setSelectedIndex(2);
            break;
            case "Choir":
            cboMinistry.setSelectedIndex(3);
            break;
            case "Ushering & Hospitality":
            cboMinistry.setSelectedIndex(4);
            break;
            case "Intercessory":
            cboMinistry.setSelectedIndex(5);
            break;
            case "Creativity":
            cboMinistry.setSelectedIndex(6);
            break;
            case "Instrunments":
            cboMinistry.setSelectedIndex(7);
            break;
            case "High School":
            cboMinistry.setSelectedIndex(8);
            break;
                
        }

        String year=model.getValueAt(row, 6).toString();
        switch(year){
            case "First Year":
            CboYear.setSelectedIndex(1);
            break;
            case "Second Year":
            CboYear.setSelectedIndex(2);
            break;
            case "Third Year":
            CboYear.setSelectedIndex(3);
            break;
            case "Fourth Year":
            CboYear.setSelectedIndex(4);
            break;
           
        }

       String Et=model.getValueAt(row, 7).toString();
        switch(Et){
            case "CET":
            cboEt.setSelectedIndex(1);
            break;
            case "NET":
            cboEt.setSelectedIndex(2);
            break;
            case "WESO":
            cboEt.setSelectedIndex(3);
            break;
            case "RIVET":
            cboEt.setSelectedIndex(4);
            break;
            case "ESET":
            cboEt.setSelectedIndex(4);
            break;
           
        }
        
       
    }//GEN-LAST:event_tableShowMembersMouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
//        this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void CboYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CboYearActionPerformed

    private void txtFirst_NameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFirst_NameKeyTyped
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtFirst_NameKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CboYear;
    private javax.swing.JTextField QuickSearch;
    private javax.swing.JRadioButton Radio_Female;
    private javax.swing.JRadioButton Radio_Male;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox cboEt;
    private javax.swing.JComboBox cboMinistry;
    private javax.swing.JLabel fName;
    private javax.swing.JLabel fName1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelShowTime;
    private javax.swing.JLabel lastName;
    public static javax.swing.JLabel showDate;
    private javax.swing.JTable tableShowMembers;
    private javax.swing.JTextField txtFirst_Name;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtLast_Name;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtRegNumber;
    // End of variables declaration//GEN-END:variables

private void insert(){

        int components;
        Connection con=null;
        ResultSet rs=null;
        Statement st;
        PreparedStatement pst=null;
      
        try{
        
           String dbname="cu";
            String pass="";
            String username="root";
            String Url="jdbc:mysql://localhost:3306/";
            String Drivers="com.mysql.jdbc.Driver";

            Class.forName(Drivers);
            con=DriverManager.getConnection(Url+dbname,username,pass);
            String Gender;
            if(Radio_Female.isSelected()){
            Gender="Female";
            }else{
            Gender="Male";
            }
           String Year=(String) CboYear.getSelectedItem();
                switch (Year) {
                    case "First Year":
                        Year="1";
                        break;
                    case "Second Year":
                        Year="2";
                        break;
                    case "Third Year":
                        Year="3";
                        break;
                    case "Fourth Year":
                        Year="4";
                        break;
                }
                String fname=txtFirst_Name.getText();
                String lname=txtLast_Name.getText();
                String name= fname+" "+lname;
           String sql="INSERT INTO registerMembers(Name,Reg_Number,"
        + "Gender,PhoneNumber,Ministry,Year,ET)VALUES('"+name+"','"+txtRegNumber.getText()+"','"+Gender+"',"
       + "'"+txtPhoneNumber.getText()+"','"+cboMinistry.getSelectedItem()+"','"+Year+"',"
         + "'"+cboEt.getSelectedItem()+"')";
            pst=con.prepareStatement(sql);
            pst.execute();
            //confirm data submission
           int saveExec;
      saveExec=  JOptionPane.showConfirmDialog(null,"Are you Sure you\n want to "
      + "Save Data?","SAVE",JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE);
      
      if(saveExec==JOptionPane.YES_NO_OPTION){
            
          showResultsOnTable(); 
          FeeReminder f= new FeeReminder();
          f.selectData();
        
      }
      //show error when empty fields submitted
        }catch(Exception ex){
           
        txtFirst_Name.setBorder(new LineBorder(Color.red));
        txtLast_Name.setBorder(new LineBorder(Color.red));
        txtPhoneNumber.setBorder(new LineBorder(Color.red));
        cboMinistry.setBorder(new LineBorder(Color.red));
        cboEt.setBorder(new LineBorder(Color.red));
        Radio_Female.setBorder(new LineBorder(Color.red));
        Radio_Male.setBorder(new LineBorder(Color.red));
        txtRegNumber.setBorder(new LineBorder(Color.red));
      JOptionPane.showMessageDialog(this,"All Fields Required!"+ex.getLocalizedMessage());
        }
     
     }
 //clear all field texts
 private  void reset(){
 
       btnReset.setEnabled(true);
       txtFirst_Name.setText("");
       txtLast_Name.setText("");
       txtPhoneNumber.setText("+2547");
       txtRegNumber.setText("");
       cboMinistry.setSelectedIndex(0);
       cboEt.setSelectedIndex(0);
       txtLast_Name.setVisible(true);
       lastName.setVisible(true);
       fName.setVisible(true);
       
       
 
 
 }
 private void normaBorder(){
     
 
 }
 //display records on table
 public void showResultsOnTable(){
     try{
         Connection conn=null;
         PreparedStatement pst= null;
         ResultSet rs;
        conn= DriverManager.getConnection("jdbc:mysql://localhost:3306/cu","root","");
        String sql="SELECT * FROM registermembers ORDER BY Id Asc";
        pst=conn.prepareStatement(sql);
        rs= pst.executeQuery();
        tableShowMembers.setModel(DbUtils.resultSetToTableModel(rs));
       

     }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
     
     }
 
 }
 public void searchRecords(){
      DefaultTableModel model=(DefaultTableModel) tableShowMembers.getModel();
                model.setRowCount(0);
      int components;
        Connection con=null;
        ResultSet rs=null;
        Statement st;
        PreparedStatement pst=null;
      
        try{
        
           String dbname="cu";
            String pass="";
            String username="root";
            String Url="jdbc:mysql://localhost:3306/";
            String Drivers="com.mysql.jdbc.Driver";

            Class.forName(Drivers);
            con=DriverManager.getConnection(Url+dbname,username,pass);
            String sql="SELECT * FROM registermembers WHERE Reg_Number LIKE '%"+QuickSearch.getText()+"%' || First_Name LIKE '%"+QuickSearch.getText()+"%' || PhoneNumber LIKE '%"+QuickSearch.getText()+"%' ORDER BY Id ASC";
                int count=0;
            pst=con.prepareStatement(sql);
            pst.execute();
            model=(DefaultTableModel)tableShowMembers.getModel();
           
            if (rs.next()){
                
             // model.setRowCount(model.getRowCount()+1);
                String id=rs.getString("ID");  
                String fn=rs.getString("Name");
              //  String ln=rs.getString("Last_Name");
                String reg=rs.getString("Reg_Number");
                String gd=rs.getString("Gender");
                String phn=rs.getString("PhoneNumber");
                String jm=rs.getString("Ministry");
                String yr=rs.getString("Year");
                String em=rs.getString("ET");
             

                model.addRow(new Object[]{id,fn,reg,gd,phn,jm,yr,em});
                        cboEt.setSelectedItem(em);
                    
           }
            
            if(model.getRowCount()==0){
            JOptionPane.showMessageDialog(this,"No Record Match!");
            
            }else{
            
            }
//            if(rs.equals(0)){
//            JOptionPane.showMessageDialog(this,"No record Found");
//            
//            }
            //confirm data submission
      //show error when empty fields submitted
        }catch(Exception ex){
       
 
        }
 
 }public void updateRecords(){
     
     try{
         int row=tableShowMembers.getSelectedRow();
         String value=(tableShowMembers.getModel().getValueAt(row, 0).toString());
     String sql="UPDATE registermembers SET Name =?,Reg_Number =?,Gender=?,PhoneNumber =?,Ministry =?,Year=?,ET=? WHERE Id="+value;
     Connection conn=null;
         PreparedStatement pst= null;
         ResultSet rs;
        conn= DriverManager.getConnection("jdbc:mysql://localhost:3306/cu","root","");
           pst= conn.prepareStatement(sql);
                String fname=txtFirst_Name.getText();
                String lname=txtLast_Name.getText();
                String name= fname+" "+lname;
        pst.setString(1,name);
        pst.setString(2, txtRegNumber.getText());
           String Gender;
            if(Radio_Female.isSelected()){
            Gender="Female";
            }else{
            Gender="Male";
            }
        pst.setString(3,Gender);
        pst.setString(4, txtPhoneNumber.getText());
        pst.setString(5,(String) cboMinistry.getSelectedItem());
          String Year=(String) CboYear.getSelectedItem();
                switch (Year) {
                    case "First Year":
                        Year="1";
                        break;
                    case "Second Year":
                        Year="2";
                        break;
                    case "Third Year":
                        Year="3";
                        break;
                    case "Fourth Year":
                        Year="4";
                        break;
                }
                
        pst.setString(6, Year);
        pst.setString(7, (String)cboEt.getSelectedItem());
                 pst.executeUpdate();
                DefaultTableModel model= (DefaultTableModel)tableShowMembers.getModel();
                model.setRowCount(0);
                showResultsOnTable();
                JOptionPane.showMessageDialog(this,"One Record Updated!");
                txtLast_Name.setVisible(true);
                lastName.setVisible(true);
                fName.setVisible(true);
     }catch(Exception e){
     
          JOptionPane.showMessageDialog(this,e);
     
     }
 
 
 }
 public void deleteRecords(){
        dbConnect connect= new dbConnect();
        connect.Connect();
        try{
            DefaultTableModel model=(DefaultTableModel)tableShowMembers.getModel();
            
         int select= tableShowMembers.getSelectedRow();
       //  Object Reg_Number=tableShowMembers.getValueAt(select,0).toString();
//         txId.setText(model.getValueAt(select, 0).toString());
         txtFirst_Name.setText(model.getValueAt(select, 0).toString());
        // txtLast_Name.setText(model.getValueAt(select, 2).toString());
         txtRegNumber.setText(model.getValueAt(select, 2).toString());
         String gender=model.getValueAt(select, 3).toString();
            if(gender.equals("Male")){
                Radio_Male.setSelected(true);
            }else{
                Radio_Female.setSelected(true);
            }
         txtPhoneNumber.setText(model.getValueAt(select, 4).toString());
          String Ministry=model.getValueAt(select, 5).toString();
           switch(Ministry){
            case "Praise & Worship":
            cboMinistry.setSelectedIndex(1);
            break;
            case "Church School":
            cboMinistry.setSelectedIndex(2);
            break;
            case "Choir":
            cboMinistry.setSelectedIndex(3);
            break;
            case "Ushering & Hospitality":
            cboMinistry.setSelectedIndex(4);
            break;
            case "Intercessory":
            cboMinistry.setSelectedIndex(5);
            break;
            case "Creativity":
            cboMinistry.setSelectedIndex(6);
            break;
            case "Instrunments":
            cboMinistry.setSelectedIndex(7);
            break;
            case "High School":
            cboMinistry.setSelectedIndex(8);
            break;
                
        }
          String year=model.getValueAt(select, 6).toString();
            switch(year){
                case "First Year":
                    CboYear.setSelectedIndex(1);
                    break;
                case "Second Year":
                    CboYear.setSelectedIndex(2);
                    break;
                case "Third Year":
                    CboYear.setSelectedIndex(3);
                    break;
                case "Fourth Year":
                    CboYear.setSelectedIndex(4);
                    break;
                case "Associate":
                   CboYear.setSelectedIndex(5);
                    break;
                case "Allumini":
                    CboYear.setSelectedIndex(6);
                    break; 
                case "Guest":
                    CboYear.setSelectedIndex(7);
                    break;
            }
String Et=model.getValueAt(select, 7).toString();
        switch(Et){
            case "CET":
            cboEt.setSelectedIndex(1);
            break;
            case "NET":
            cboEt.setSelectedIndex(2);
            break;
            case "WESO":
            cboEt.setSelectedIndex(3);
            break;
            case "RIVET":
            cboEt.setSelectedIndex(4);
            break;
            case "ESET":
            cboEt.setSelectedIndex(4);
            break;
           
        }       

         showResultsOnTable();
        }catch(Exception e){
        JOptionPane.showMessageDialog(this,e.getLocalizedMessage());
        }
    }
 
 public void timer(){

     Thread clock= new Thread(){
         public void run(){
         
         for(;;){
          Calendar cal = new GregorianCalendar();
          SimpleDateFormat sdf= new SimpleDateFormat("HH:mm:ss a");

          labelShowTime.setText(sdf.format(cal.getTime()));
         try{
             sleep(1000);
         }catch(Exception ex){
         
             JOptionPane.showMessageDialog(null, ex);
         
         }
         }
         }
         
                };
         clock.start();
                 }
 
 public void table_filter(){
         
        
            DefaultTableModel model=(DefaultTableModel) tableShowMembers.getModel();
                model.setRowCount(0);
      
        int component;
        Connection con=null;
        ResultSet rs;
        Statement st;
        PreparedStatement pst=null;

        try{
            String dbname="cu";
            String pass="";
            String username="root";
            String Url="jdbc:mysql://localhost:3306/";
            String Drivers="com.mysql.jdbc.Driver";

            Class.forName(Drivers);

            con=DriverManager.getConnection(Url+dbname,username,pass);
            String sql="SELECT * FROM registermembers WHERE Name LIKE '%"+QuickSearch.getText()+"%' || Reg_Number LIKE '%"+QuickSearch.getText()+"%' ORDER BY Id ASC";

            st=con.createStatement();
            rs=st.executeQuery(sql);
            model=(DefaultTableModel)tableShowMembers.getModel();
           
            while (rs.next()){
                
             // model.setRowCount(model.getRowCount()+1);
                 String id=rs.getString("ID");  
                String ln=rs.getString("Name");
                String reg=rs.getString("Reg_Number");
                String gd=rs.getString("Gender");
                String p=rs.getString("PhoneNumber");
                String jm=rs.getString("Ministry");
                String yr=rs.getString("Year");
                String em=rs.getString("ET");
                
                model.addRow(new Object[]{id,ln,reg,gd,p,jm,yr,em});
                   
           }
            
            if(model.getRowCount()==0){
            JOptionPane.showMessageDialog(this,"No Record Match!");
            
            }else{
            
            }
//            JOptionPane.showMessageDialog(this,"No RECORD FOUND");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,"NO RECORDS FOUND!");
        }
     }
 private void date(){
     
     Date d= new Date();
     String show= d.toString();
     showDate.setText(show);
 }
 
 
 public class FeeReminder {

    String message = "";
    PreparedStatement pst;
    ResultSet rs;
    String data[] = new String[7];

    private void selectData() throws SQLException {
       Connect c= new Connect();
       c.connect();

        pst = Mysql.connect("sms_project")
                .prepareStatement("select Name,Reg_Number,gender,phoneNumber,ministry,Year,ET from Reg_Number WHERE Reg_Number LIKE '%"+QuickSearch.getText()+"%' || name LIKE '%"+QuickSearch.getText()+"%'");
//            Logger.getLogger(CA.class.getName()).log(Level.SEVERE, null, ex);

        try {
            rs = pst.executeQuery();
            while (rs.next()) {
                data[0] = rs.getString("Name");
                 data[1] = rs.getString("Reg_Number");
                  data[2] = rs.getString("gender");
                    data[3] = rs.getString("phoneNumber");
                     data[4] = rs.getString("ministry");
                      data[5] = rs.getString("Year");
                       data[6] = rs.getString("ET");
                
                message = processMessage(data);

                sendSMS(rs.getString("phoneNumber"));
            }
        } catch (SQLException ex) {
//            Logger.getLogger(CA.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    private String processMessage(String data[]) {
        String name=data[0];
       // String =data[3];
        String ministry=data[4];
        String et=data[6];
      
//    message = "Dear {sex}{name}! Lechall33 now .kindly hurry.Bash kick starts.Thanks";
//    message = "Dear {sex}."+parent+"! your student {name} has payed Ksh."+payed+" via "+mode+". Outstanding fee balance for this year is Ksh."+balance+".Thank you ";
        message = "Dear "+name+"! You have successfuly been registered as a member of Kisii University Christian Union. Your ministry is "+ministry+" Thanks.";

        String sex = data[2].equalsIgnoreCase("Male") ? "Mr." : "Miss.";
       
         
        return message.replace("{name}", " " + data[0] + " ").replace("{sex}", sex);
    }

    private void sendSMS(String recepient) {
        try {
            pst = Mysql.connect("sms_project").
                    prepareStatement("INSERT INTO outbox(receiver,msg,msgtype,sender)"
                            + " VALUES(?,?,?,?)");
            pst.setString(1, recepient);
            pst.setString(2, message);
            pst.setString(3, "sms.text");
            pst.setString(4, "+2547");

        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
        try {
            pst.execute();
        } catch (SQLException ex) {
        }
        Icon icon = new ImageIcon(getClass().getResource("/ter/icons/10.gif"));
        JOptionPane.showMessageDialog(null, "Sending messages...","",JOptionPane.INFORMATION_MESSAGE,icon);
    }
//
//    public static void main(String[] args) {
//       FeeReminder f= new FeeReminder();
//       f.selectData();
    }
     

}
